import clsx from "clsx";
import "./globals.css";
import { inter } from "./fonts";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { Section } from "@/components/section";
import { SECTION_LAST_PROPS } from "@/content/home";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx("flex flex-col bg-secondary min-h-screen gap-20", inter.className)}>
        {/* HEADER */}
        <Header />

        {/* CONTENT */}
        <main>{children}</main>

        {/* FOOTER */}
        <Section {...SECTION_LAST_PROPS} paper />
        <Footer />
      </body>
    </html>
  );
}
